name: preserve
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  #remove later
  args: ^2.4.2
  custom_lint: ^0.6.0
  get_it: ^7.6.7
  oauth2: ^2.0.2
  open_url: ^2.0.1
  riverpod: ^2.5.0
  riverpod_annotation: ^2.3.4
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2
  spotify: ^0.13.0
  yaml: ^3.1.2
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.8
  lints: ^2.1.0
  test: ^1.24.0
